CREATE TABLE PATIENTS(
   SSN VARCHAR(9) NOT NULL,
   FIRSTNAME varchar(255) NOT NULL,
   LASTNAME varchar(255) NOT NULL,
   SEX VARCHAR(1) NOT NULL,
   DATE_OF_BIRTH DATE NOT NULL,
   POSTAL_CODE VARCHAR(4) NOT NULL,
   CITY VARCHAR(255) NOT NULL,
   PRIMARY KEY ( SSN )
);